### ISSUE TITLE
kaliveda compilation in MacOs

### ISSUE THREAD

**Issue by chbihi** [kaliveda-dev/kaliveda#114]
error report in compiling kaliveda in MacOs.

cmake S -DCMAKE_INSTALL_PREFIX=I
make -j 4 install

[ 94%] Built target KVMultiDetdb_sqlite_examples
[ 94%] Built target KVMultiDetbase_kvnumberlist
[ 94%] Building CXX object MicroStat/CMakeFiles/MicroStatMicroStat_example.dir/examples/MicroStat_example.C.o
[ 94%] Building CXX object MicroStat/CMakeFiles/MicroStatMicroStat_example2.dir/examples/MicroStat_example2.C.o
/Users/chbihi/software/kaliveda/kaliveda-sources/KVMultiDet/examples/globvars_kvzmax.C:81:7: error: use of undeclared identifier 'random_shuffle'
      random_shuffle(zlist.begin(), zlist.end()); // see http://www.cplusplus.com/reference/algorithm/random_shuffle
      ^
1 error generated.
make[2]: *** [KVMultiDet/CMakeFiles/KVMultiDetglobvars_kvzmax.dir/examples/globvars_kvzmax.C.o] Error 1
make[1]: *** [KVMultiDet/CMakeFiles/KVMultiDetglobvars_kvzmax.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 94%] Linking CXX shared library ../lib/libMicroStatMicroStat_example.dylib
[ 94%] Built target MicroStatMicroStat_example
[ 95%] Linking CXX shared library ../lib/libMicroStatMicroStat_example2.dylib
[ 95%] Linking CXX shared library ../lib/libKVMultiDetglobvars_test.dylib
[ 95%] Built target MicroStatMicroStat_example2
[ 95%] Built target KVMultiDetglobvars_test
make: *** [all] Error 2
ganm217:kaliveda-build chbihi$

**Comment by jdfrankland** [comment]
fixed in dev branch

**Comment by chbihi** [comment]
thank you John

**Comment by chbihi** [comment]
the problem of compilation remains. The same compilation error random_chuffle.
``
