### ISSUE TITLE
can't read FAZIA recon data with option ReadRawData=1

### ISSUE THREAD

**Issue by jdfrankland** [kaliveda-dev/kaliveda#47]
This error occurs every time you put ReadRawData=1 in the analysis

[...]
TClonesArray::Streamer expecting class
Error in <TBufferFile::ReadClassBuffer>: class: KVNameValueList, attempting to access a wrong version: 1024, object skipped at offset 93
TClonesArray::Streamer expecting class nal
Error in <TBufferFile::ReadClassBuffer>: class: KVNameValueList, attempting to access a wrong version: 11601, object skipped at offset 223
TClonesArray::Streamer expecting class
Error in <TBufferFile::ReadClassBuffer>: class: KVNameValueList, attempting to access a wrong version: 1024, object skipped at offset 93
TClonesArray::Streamer expecting class nal
Error in <TBufferFile::ReadClassBuffer>: class: KVNameValueList, attempting to access a wrong version: 11601, object skipped at offset 223
TClonesArray::Streamer expecting class nal
Error in <TBufferFile::ReadClassBuffer>: class: KVNameValueList, attempting to access a wrong version: 11601, object skipped at offset 223
TClonesArray::Streamer expecting class
Error in <TBufferFile::ReadClassBuffer>: class: KVNameValueList, attempting to access a wrong version: 1024, object skipped at offset 93
[...]

**Comment by GiuseppePast** [comment]
I was working on a macro Test.C to save in the final tree also the signal QH1 and I1 because one student here in Florence is working on the timing property of the Fazia Silicon detector. If I put ReadRawData=1 in KalivedaGui this error occurs. Without this option Test.C doesn't give any error but obviously it doesn't work on signal (starting from the recon file). Any ideas?

**Comment by jdfrankland** [comment]
OK I'll investigate. Any particular run (in ISOFAZIA dataset?) ?

**Comment by GiuseppePast** [comment]
I tried with the ISOFAZIA runs of 48Ca system. I didn't tried any other dataset.
